name: Rust

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: '${{ github.workspace }}/target/example.profraw'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: package coverage
      run: llvm-profdata merge -sparse $LLVM_PROFILE_FILE -o '${{ github.workspace }}/target/example.profdata'
