name: Rust

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: '${{ github.workspace }}/crate-%p-%m.profraw'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup toolchain install stable --component llvm-tools-preview
    - name: Update path for llvm files
      run: echo "/usr/lib/llvm-14/bin" >> $GITHUB_PATH
    - name: test
      run: cargo test
    - name: bundle coverage
      run: llvm-profdata merge -sparse crate-*.profraw -o crate.profdata
    - name: convert to lcov
      run: llvm-cov export --instr-profile=crate.profdata --format=lcov \
        $( 
          for file in 
            $( 
              cargo test --tests --no-run --message-format=json 
                | jq -r "select(.profile.test == true) | .filenames[]" 
                | grep -v dSYM - 
            ); 
          do 
            printf "%s %s " -object $file; 
          done 
        ) \
        > lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: lcov.info
        fail_ci_if_error: true